In [1]:
import numpy as np
import pandas as pd
import cv2
import os
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import pywt
from skimage.feature import hog
from skimage.transform import resize
data_path="E:\\Panduranga\\Downloads\\caltech101\\101_ObjectCategories"
files = os.listdir(data_path)
cat=[]
for name in files:
    cat+=[name]

In [3]:
from skimage.transform import resize
from skimage.feature import hog
fd_trainH=[]
fd_trainV=[]
fd_trainD=[]
fd_trainA=[]

for i in cat:
    path=os.path.join(data_path,i)
    print(i)
    for img in os.listdir(path):
        image=os.path.join(path,img)
         
        train_data=cv2.imread(image)
        
        #Principal component analysis
        blue,green,red = cv2.split(train_data)
        #it will split the original image into Blue, Green and Red arrays.
        #initialize PCA with first 50 principal components
        pca = PCA(50)

        #Applying to red channel and then applying inverse transform to transformed array.
        red_transformed = pca.fit_transform(red)
        red_inverted = pca.inverse_transform(red_transformed)

        #Applying to Green channel and then applying inverse transform to transformed array.
        green_transformed = pca.fit_transform(green)
        green_inverted = pca.inverse_transform(green_transformed)

        #Applying to Blue channel and then applying inverse transform to transformed array.
        blue_transformed = pca.fit_transform(blue)
        blue_inverted = pca.inverse_transform(blue_transformed)

        img_compressed = (np.dstack((red_inverted, green_inverted, blue_inverted))).astype(np.uint8)
        img=cv2.cvtColor(img_compressed,cv2.COLOR_BGR2GRAY)
        img = resize(img, (128, 64))
        
        #Daubechies Wavelet
        coeffs2 = pywt.dwt2(img, 'db2')
        LL, (LH, HL, HH) = coeffs2
        
        # Approximation
        fdA, hog_image = hog(LL, orientations=9, pixels_per_cell=(8, 8),cells_per_block=(2, 2), visualize=True)
        fd_trainA +=[ np.append(fdA,cat.index(i))]
        
        # Horizontal
        fdH, hog_image = hog(LH, orientations=9, pixels_per_cell=(8, 8),cells_per_block=(2, 2), visualize=True)
        fd_trainH +=[ np.append(fdH,cat.index(i))]
        
        #Vertical
        fdV, hog_image = hog(HL, orientations=9, pixels_per_cell=(8, 8),cells_per_block=(2, 2), visualize=True)
        fd_trainV +=[ np.append(fdV,cat.index(i))]
        
        #diagonal
        fdD, hog_image = hog(HH, orientations=9, pixels_per_cell=(8, 8),cells_per_block=(2, 2), visualize=True)
        fd_trainD +=[ np.append(fdD,cat.index(i))]
        


accordion
airplanes
anchor
ant
BACKGROUND_Google
barrel
bass
beaver
binocular
bonsai
brain
brontosaurus
buddha
butterfly
camera
cannon
car_side
ceiling_fan
cellphone
chair
chandelier
cougar_body
cougar_face
crab
crayfish
crocodile
crocodile_head
cup
dalmatian
dollar_bill
dolphin
dragonfly
electric_guitar
elephant
emu
euphonium
ewer
Faces
Faces_easy
ferry
flamingo
flamingo_head
garfield
gerenuk
gramophone
grand_piano
hawksbill
headphone
hedgehog
helicopter
ibis
inline_skate
joshua_tree
kangaroo
ketch
lamp
laptop
Leopards
llama
lobster
lotus
mandolin
mayfly
menorah
metronome
minaret
Motorbikes
nautilus
octopus
okapi
pagoda
panda
pigeon
pizza
platypus
pyramid
revolver
rhino
rooster
saxophone
schooner
scissors
scorpion
sea_horse
snoopy
soccer_ball
stapler
starfish
stegosaurus
stop_sign
strawberry
sunflower
tick
trilobite
umbrella
watch
water_lilly
wheelchair
wild_cat
windsor_chair
wrench
yin_yang


In [5]:
np.savetxt('HOG_PCS50_dbWaveletA.csv',fd_trainA, delimiter=',',fmt='%f')
np.savetxt('HOG_PCS50_dbWaveletH.csv',fd_trainH, delimiter=',',fmt='%f')
np.savetxt('HOG_PCS50_dbWaveletV.csv',fd_trainV, delimiter=',',fmt='%f')
np.savetxt('HOG_PCS50_dbWaveletD.csv',fd_trainD, delimiter=',',fmt='%f')

# Machine Learning

## Logistic Regression

In [6]:
import pandas as pd
import numpy as np
# load the training dataset
#images = pd.read_csv('array1.csv',header=None)
images = pd.read_csv('HOG_PCS50_dbWaveletA.csv',header=None)
images

0         1         2         3         4         5         6    \
0     0.234803  0.248588  0.136302  0.121093  0.210252  0.123376  0.097966   
1     0.388997  0.388997  0.202880  0.037811  0.366877  0.000000  0.000000   
2     0.139069  0.075187  0.131507  0.092885  0.207594  0.148463  0.086753   
3     0.188939  0.249757  0.105425  0.154262  0.251360  0.068356  0.084283   
4     0.231749  0.172544  0.126384  0.234780  0.299435  0.004545  0.073975   
...        ...       ...       ...       ...       ...       ...       ...   
9140  0.199468  0.136590  0.042501  0.068924  0.107564  0.021488  0.069620   
9141  0.233853  0.054863  0.083962  0.084290  0.195049  0.091566  0.146469   
9142  0.161382  0.027037  0.044851  0.021378  0.078243  0.094981  0.105885   
9143  0.026826  0.025372  0.027642  0.002002  0.011808  0.006158  0.005703   
9144  0.243880  0.063607  0.028833  0.092769  0.124824  0.114988  0.048647   

           7         8         9    ...       747       748       749  \
0     0.107737  0.111874  0.248588  ...  0.230711  0.275870  0.280130   
1     0.000000  0.062623  0.119384  ...  0.168830  0.254303  0.254303   
2     0.151354  0.160979  0.263512  ...  0.164253  0.202408  0.167975   
3     0.078215  0.029758  0.323802  ...  0.255274  0.220984  0.255274   
4     0.002901  0.299435  0.299435  ...  0.158923  0.236805  0.236805   
...        ...       ...       ...  ...       ...       ...       ...   
9140  0.000000  0.125875  0.244789  ...  0.244888  0.221858  0.102411   
9141  0.064501  0.255388  0.008955  ...  0.144639  0.000000  0.000000   
9142  0.022119  0.084969  0.397459  ...  0.109284  0.148033  0.031822   
9143  0.004250  0.006807  0.283542  ...  0.159314  0.308855  0.115818   
9144  0.000000  0.106212  0.062344  ...  0.114591  0.033619  0.035524   

           750       751       752       753       754       755    756  
0     0.254020  0.222008  0.143890  0.040110  0.090846  0.141809    0.0  
1     0.120459  0.139923  0.072708  0.254303  0.097498  0.207117    0.0  
2     0.137825  0.113543  0.167231  0.093886  0.125813  0.195165    0.0  
3     0.088429  0.244567  0.124272  0.092321  0.085413  0.165380    0.0  
4     0.236805  0.073111  0.236805  0.101984  0.121253  0.236805    0.0  
...        ...       ...       ...       ...       ...       ...    ...  
9140  0.102681  0.103094  0.143182  0.074362  0.024354  0.146195  101.0  
9141  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  101.0  
9142  0.008892  0.020480  0.002799  0.045229  0.052213  0.083616  101.0  
9143  0.215310  0.039685  0.009087  0.004203  0.039069  0.014981  101.0  
9144  0.007579  0.045943  0.028185  0.020622  0.011056  0.084413  101.0  

[9145 rows x 757 columns]

In [7]:
X,y=images[range(756)].values,images[756].values

In [8]:
X

array([[0.234803, 0.248588, 0.136302, ..., 0.04011 , 0.090846, 0.141809],
       [0.388997, 0.388997, 0.20288 , ..., 0.254303, 0.097498, 0.207117],
       [0.139069, 0.075187, 0.131507, ..., 0.093886, 0.125813, 0.195165],
       ...,
       [0.161382, 0.027037, 0.044851, ..., 0.045229, 0.052213, 0.083616],
       [0.026826, 0.025372, 0.027642, ..., 0.004203, 0.039069, 0.014981],
       [0.24388 , 0.063607, 0.028833, ..., 0.020622, 0.011056, 0.084413]])

In [9]:
from sklearn.model_selection import train_test_split

#Split data 15%-85% into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.85, random_state=0)


In [10]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(9145, 756)
(1371, 756)
(7774, 756)


In [11]:
from sklearn.linear_model import LogisticRegression

# Set regularization rate
reg = 1

# train a logistic regression model on the training set
model = LogisticRegression(C=1/reg, solver="liblinear").fit(X_train, y_train)
print (model)

LogisticRegression(solver='liblinear')


In [12]:
predictions = model.predict(X_test)
print('Predicted labels: ', predictions)
print('Actual labels:    ' ,y_test)

Predicted labels:  [30. 27. 35. ... 89. 35. 76.]
Actual labels:     [30. 27. 35. ... 89. 23. 76.]


In [13]:
from sklearn.metrics import accuracy_score

print('Accuracy: ', accuracy_score(y_test, predictions))

Accuracy:  0.4406997684589658


In [14]:
from sklearn. metrics import classification_report

print(classification_report(y_test, predictions))

C:\Users\PC\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

         0.0       0.67      0.33      0.44        49
         1.0       0.81      0.94      0.87       686
         2.0       0.00      0.00      0.00        39
         3.0       0.00      0.00      0.00        39
         4.0       0.15      0.51      0.23       410
         5.0       0.38      0.22      0.28        36
         6.0       0.00      0.00      0.00        48
         7.0       0.00      0.00      0.00        43
         8.0       0.00      0.00      0.00        29
         9.0       0.15      0.39      0.21       104
        10.0       0.25      0.24      0.24        83
        11.0       0.00      0.00      0.00        38
        12.0       0.45      0.24      0.31        72
        13.0       0.18      0.17      0.17        78
        14.0       0.60      0.07      0.12        44
        15.0       0.20      0.06      0.10        32
        16.0       0.78      0.80      0.79       107
        17.0       0.22    

In [15]:
from sklearn.metrics import confusion_matrix

# Print the confusion matrix
cm = confusion_matrix(y_test, predictions)
print (cm)

[[ 16   0   0 ...   0   0   0]
 [  0 645   0 ...   0   0   0]
 [  0   3   0 ...   0   0   0]
 ...
 [  0   2   0 ...   4   0   0]
 [  0  10   0 ...   0   0   0]
 [  0   0   0 ...   0   0   9]]
